name: SDK PR Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on PR
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sanity-check:
    name: PR Sanity Check
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_FOR_SMART_CONTRACTS: ${{ secrets.S3_BUCKET_FOR_SMART_CONTRACTS }}
      CONTRACT_VERSION: ${{ secrets.CONTRACT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install yarn dependencies
        run: yarn --frozen-lockfile

      - name: Import typechain files from the s3 bucket
        run: yarn build

      - name: Check Typescript compilation errors
        run: yarn tsc

      - name: Check formatting errors using prettier
        run: yarn format

      - name: Check linting errors using eslint
        run: yarn lint

      - name: Build and run tests.
        run: cd src/core &&  yarn test
